### ISSUE TITLE
User configs should be separated from main script

### ISSUE THREAD

**Issue by hooliowobbits** [dajusc/Linux-Mouse-Keybinds#2]
Hi, I did a `git status` in preparation to pull down the changes made for #1 and i was told i had made local changes.  
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   linuxmousekeybinds.py

no changes added to commit (use "git add" and/or "git commit -a")
```
This is correct, as that is required in order to make the software work for our devices/games.  I will need to stash these changes in order to pull down the updated code and manually merge my configs in.

Imho it would be preferable if my own configs were in a separate file that was also being ignored by git.  One way to make this work might be to ship a example config as part of the repo, and in order for the script to run users must copy the example config to the correct name before execution.

**Comment by dajusc** [comment]
It is already possible to separate your personal config to avoid such problems. Minimum example for a separate config file would be:
```
from linuxmousekeybinds import *

lmkb = linuxmousekeybinds("Logitech G500s Laser Gaming Mouse")
lmkb.bind_key_to_button("Tomb Raider", "BTN_EXTRA",   "3") 
lmkb.run(in_new_thread=False)
```
Your config file can be located outside the "_linuxmousekeybinds.py_" repository. Just add the path to the folder containing "_linuxmousekeybinds.py_" to the systems search path. That can even be done from within your config file by prepending:
```
import sys
sys.path.append("/PATH/TO/LMKB/")
```
The reason why in the README.md I give instructions to make your config within the "_linuxmousekeybinds.py_" itself is, that it works immediately. But I'll think about adding an additional separate config file example.

**Comment by dajusc** [comment]
I followed your suggestions. You will once have to move your configuration manually to the separate file named "*my-lmkb-config.py*". Please test and close this issue if it works for you @hooliowobbits .

**Comment by hooliowobbits** [comment]
Hi mate, nice work and that worked perfectly. Thanks for that, now i can stay abreast of the new features :) But having been here once before I have found that configs will now grow stale as the application develops (and users may miss out on new config options).  It might be nice to have the application tell the user that this is the case at start up.  You could achieve that by:
1. Use semver (or similar) to give LMKB releases a version number.
1. Write that same version number to the config template.
1. When the users starts LMKB if the version number in the config differs from the LMKB version then remind the user to have a look at the .template and try the new features.

**Comment by dajusc** [comment]
Good to hear that the separate config file works for you. :)

Your suggestions about version numbering and user notification might be a good/necessary thing for software that is automatically updated by a store, package manager or by an auto-updater. But anyone who uses LMKB and wants/needs to update will have to "git pull" or download the newest version manually. On that occasion the user will likely get the idea to look into the readme or the template config, in case he is interested in new features or in enhancing his existing configuration.

After all, I intended LMKB to be a lightweight script solution for linux users who know what they are doing. Splitting the code into more than one file was already a compromise. ;) But hey, it's under GPL, so anyone is free to implement an auto-updater, systemd service or even a GUI for it. But please don't... Rather use [Piper](https://github.com/libratbag/piper) if you are into that, provided that it works for you (for me it didn't).
