### ISSUE TITLE
I am unable to get Linux-Mouse-Keybinds to work

### ISSUE THREAD

**Issue by hooliowobbits** [dajusc/Linux-Mouse-Keybinds#3]
As per your previous suggestion I have setup my config to attach an output to each button and then targetted an instance of the Pluma text editor (PID 3274) to test:
```
    lmkb = linuxmousekeybinds("Logitech G300s Optical Gaming Mouse")

    lmkb.bind_key_to_button(3274, "BTN_LEFT",   "1")   #
    lmkb.bind_key_to_button(3274, "BTN_MOUSE",  "2")   #
    lmkb.bind_key_to_button(3274, "BTN_RIGHT",  "3")   #
    lmkb.bind_key_to_button(3274, "BTN_MIDDLE", "4")   #
    lmkb.bind_key_to_button(3274, "BTN_SIDE",   "5")   #
    lmkb.bind_key_to_button(3274, "BTN_EXTRA",  "6")   #
    lmkb.bind_key_to_button(3274, "BTN_FORWARD","7")   #  
    lmkb.bind_key_to_button(3274, "BTN_BACK",   "8")   #
    lmkb.bind_key_to_button(3274, "BTN_TASK",   "9")   # 
    lmkb.bind_key_to_button(3274, "REL_X+",     "0")   # 
    lmkb.bind_key_to_button(3274, "REL_X-",     "a")   # 
    lmkb.bind_key_to_button(3274, "REL_Y+",     "b")   # 
    lmkb.bind_key_to_button(3274, "REL_Y-",     "c")   #
    lmkb.bind_key_to_button(3274, "REL_WHEEL+", "d")   # 
    lmkb.bind_key_to_button(3274, "REL_WHEEL-", "e")   # 
```
However I get nothing at all in Pluma.  Same same if i set the target application to None.

I am running ubuntu 18.04 and have setup Linux-Mouse-Keybinds in a dedicated conda python3 environment.  Into that environment i pip installed the dependencies, and after setting my device name and button names correctly, the application starts without error.
```
(linuxmousekeybinds) hoolio@gandalf:~/Linux-Mouse-Keybinds:$ which python
/home/hoolio/miniconda3/envs/linuxmousekeybinds/bin/python
(linuxmousekeybinds) hoolio@gandalf:~/Linux-Mouse-Keybinds:$ python --version
Python 3.8.3
(linuxmousekeybinds) hoolio@gandalf:~/Linux-Mouse-Keybinds:$ python ./linuxmousekeybinds.py 
######################################################################
Linux Mouse Keybinds started!
Active window changed to "hoolio@gandalf: /home/hoolio/Linux-Mouse-Keybinds" (PID: 2520)
Active window changed to "*Unsaved Document 1 - Pluma" (PID: 3274)
Active window changed to "hoolio@gandalf: /home/hoolio/Linux-Mouse-Keybinds" (PID: 2520)
```
I also tried with the system python (2.7) which required me to install the relevant apt packages for the two dependencies (python-evdev and python-natsort).  Again the application then started without error, but again it doesn't actually work for me.
```
hoolio@gandalf:~/Linux-Mouse-Keybinds:$ which python
/usr/bin/python
hoolio@gandalf:~/Linux-Mouse-Keybinds:$ python --version
Python 2.7.17
hoolio@gandalf:~/Linux-Mouse-Keybinds:$ python ./linuxmousekeybinds.py 
######################################################################
Linux Mouse Keybinds started!
Active window changed to "hoolio@gandalf: /home/hoolio/Linux-Mouse-Keybinds" (PID: 2520)
Active window changed to "*Unsaved Document 1 - Pluma" (PID: 3274)
```

**Comment by dajusc** [comment]
LMKB apparently detects the change of the active window, so xdotool is probably working OK. Anyway, you can check if its forward & backward translation works fine. Executing the following command in a terminal should give you the caption/name of the terminal window:
```
$ xdotool getwindowname $(xdotool getactivewindow)
```
Also try using the window name instead of the PID in your config:
```
lmkb.bind_key_to_button("*Unsaved Document 1 - Pluma", "BTN_EXTRA", "6")
```

**Comment by hooliowobbits** [comment]
hi again, through a variety of means I have been able to get it to work :) I started by reading the code and noticed that you're just calling `xdotool`; so i wondered if i could echo the cmd out to screen and so I could try and exec it manually.

So I modified the code to print out when it was executing `xdotool`:
```
    def _do_key(self, appind, keynam, down=True, up=True):
        cmd = "nice -n {} xdotool {} --window {} {}".format(self.nice, "{}", appind, keynam)
        if down:
            if self.verbose: print("executing: ", cmd)
            subprocess.Popen(cmd.format("keydown"), stdout=subprocess.PIPE, shell=True)       
        if down and up:
            time.sleep(self.delay)
        if up:
            subprocess.Popen(cmd.format("keyup"), stdout=subprocess.PIPE, shell=True)
```
which resulted in:
```
(linuxmousekeybinds) hoolio@gandalf:~/Linux-Mouse-Keybinds:$ python ./linuxmousekeybinds.py 
######################################################################
Linux Mouse Keybinds started!
Active window changed to "hoolio@gandalf: /home/hoolio/Linux-Mouse-Keybinds" (PID: 4805)
Active window changed to " test - Linux-Mouse-Keybinds - Visual Studio Code" (PID: 12570)
executing:  nice -n 0 xdotool {} --window 140509185 6
executing:  nice -n 0 xdotool {} --window 140509185 6
```
But it then became apparent that it wasn't even executing `xdotool` most of the time.  To be exact I wasn't getting LMKB to fire on all my buttons, but only on `BTN_LEFT`, `BTN_RIGHT`, `BTN_MIDDLE`,`REL_WHEEL+` and `REL_WHEEL-`.  This was because my mouse wasn't actually sending other button presses (because it's not configured to by default). 

Enter [ratslap](https://github.com/krayon/ratslap) (which only works for the g300s), where I can program the buttons to do specific things.  Here i allocate the 4 physical buttons I care about `g4`, `g5` etc to actual mouse button names `button6`, `button7` etc.  The exact mapping doesn't matter so long as LMKB sees all the buttons being pressed.
```
(base) hoolio@gandalf:~/ratslap:$ sudo ./ratslap -mf4 --g5 button6 --g4 button7 --g6 button9 --g7 button8
RatSlap v0.3.2 (BUILT: 2020-05-25 13:48:43+1000)
Copyright (C) 2016-2020 Todd Harbour
Linux configuration tool for Logitech mice (currently only G300/G300S)
https://gitlab.com/krayon/ratslap/
Found Logitech G300s (046d:c246) @ 0x5632f35e1cd0
Detaching kernel driver...
Modifying Mode: F4
    Setting button 5: button6
    Setting button 4: button7
    Setting button 6: button9
    Setting button 7: button8
Saving Mode: F4
Attaching kernel driver...
```
Then! If i ran LMKB with the following config
```
    lmkb = linuxmousekeybinds("Logitech G300s Optical Gaming Mouse")

    #../ratslap -mf4 --g5 button6 --g4 button7 --g6 button9 --g7 button8

    target = 12570

    lmkb.bind_key_to_button(target, "BTN_SIDE",   "5")   #
    lmkb.bind_key_to_button(target, "BTN_EXTRA",  "6")   #
    lmkb.bind_key_to_button(target, "BTN_FORWARD","7")   #  
    lmkb.bind_key_to_button(target, "BTN_BACK",   "8")   #
```
I start to get some sensible output in my terminal window :)
```
(linuxmousekeybinds) hoolio@gandalf:~/Linux-Mouse-Keybinds:$ python ./linuxmousekeybinds.py 
######################################################################
Linux Mouse Keybinds started!
Active window changed to "hoolio@gandalf: /home/hoolio/Linux-Mouse-Keybinds" (PID: 4805)
Active window changed to "linuxmousekeybinds.py - Linux-Mouse-Keybinds - Visual Studio Code" (PID: 12570)
executing:  nice -n 0 xdotool {} --window 140509185 5
executing:  nice -n 0 xdotool {} --window 140509185 6
executing:  nice -n 0 xdotool {} --window 140509185 7
executing:  nice -n 0 xdotool {} --window 140509185 8
```
I haven't yet tried it in the game, but at least it's working as advertised now.

**Comment by dajusc** [comment]
Glad to hear you got it working. :)

I actually had a similar issue with my Logitech G502 Lightspeed, but only with one button: The lower thumb button is originally bound to a function called "DPI shift" which basically does a quick hold&release DPI changer (who wants this?). So originally no event was generated by this button as well, until I reprogrammed the mouse with the original Logitech software to use the lower thumb button as a "normal" button.

Anyhow, its kind of strange that apparently all buttons of your G300s had this issue. That's why I didn't think of it in the first place.
