### ISSUE TITLE
add option to randomize delay time within macro function

### ISSUE THREAD

**Issue by hooliowobbits** [dajusc/Linux-Mouse-Keybinds#4]
This doesn't effect me personally and I'm not fussed if this is implemented or not, but I suspect some anti-cheat engines might not like it if they see gamers trigger a series of keypresses (via a macro) where the delay between each keypress is completely predictable.  Mitigation of that predictability by randomizing the macro delays might help some people not get banned.  Wether they _should be_ banned however is somewhat of a meta question.

**Comment by dajusc** [comment]
I think randomly timed key-press-macros can be used for other things than cheating, e.g. randomised brush strokes in GIMP. Beside that it is a minor modification that anyone with bad intentions could do anyway. So I didn't see a good reason not to implement it: Done in 36de79cae498a94da02c10392d0a348889ccb26d
