### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by MrWelsch** [dajusc/Linux-Mouse-Keybinds#7]
I have a Logitech MX Master 3 and would like to bind Ctrl and Alt to the two available side buttons which should be 8 and 9, or in the script/config: BTN_EXTRA and BTN_SIDE.

I have configured the config as follows:

lmkb.bind_key_to_button(None, “BTN_EXTRA”, “Ctrl”)
lmkb.bind_key_to_button(None, “BTN_SIDE”, “Alt”)

But it does not seem to work. Help would be much appreciated.

**Comment by dajusc** [comment]
Hey @cpsLock, I have just tested that exact configuration and ir works fine. 

On my Linux Mint Cinnamon +PY 3.7 the modifier keys work both separately (tested Ctrl+C, Ctrl+V and Alt+C) and also combined (testet Ctrl + Alt + Delete).

Maybe your mouse doensn't have those buttons. Can you check if the following config lets you insert the corresponding numbers in a textfield?
```
lmkb.bind_key_to_button(None, “BTN_EXTRA”, “1”)
lmkb.bind_key_to_button(None, “BTN_SIDE”, “2”)
```

**Comment by MrWelsch** [comment]
That won’t work either. They function as Forward and Backward Button in for example firefox and if i set a keybind ingame they are shown as MB4 and MB5.
Just tried:
lmkb.bind_key_to_button(3274, "BTN_LEFT",   "1")   #
    lmkb.bind_key_to_button(3274, "BTN_MOUSE",  "2")   #
    lmkb.bind_key_to_button(3274, "BTN_RIGHT",  "3")   #
    lmkb.bind_key_to_button(3274, "BTN_MIDDLE", "4")   #
    lmkb.bind_key_to_button(3274, "BTN_SIDE",   "5")   #
    lmkb.bind_key_to_button(3274, "BTN_EXTRA",  "6")   #
    lmkb.bind_key_to_button(3274, "BTN_FORWARD","7")   #  
    lmkb.bind_key_to_button(3274, "BTN_BACK",   "8")   #
    lmkb.bind_key_to_button(3274, "BTN_TASK",   "9")   # 
    lmkb.bind_key_to_button(3274, "REL_X+",     "0")   # 
    lmkb.bind_key_to_button(3274, "REL_X-",     "a")   # 
    lmkb.bind_key_to_button(3274, "REL_Y+",     "b")   # 
    lmkb.bind_key_to_button(3274, "REL_Y-",     "c")   #
    lmkb.bind_key_to_button(3274, "REL_WHEEL+", "d")   # 
    lmkb.bind_key_to_button(3274, "REL_WHEEL-", "e")   # 

With None instead of PIDs but none of them seemed to be applied

**Comment by dajusc** [comment]
Please post the terminal output if you miss-configure it like this:
```
lmkb.bind_key_to_button(None, "DOESNOTEXIST", "1")
```

**Comment by MrWelsch** [comment]
![image](https://user-images.githubusercontent.com/45096895/89676867-adeb9380-d8ec-11ea-936e-d4f38eaa1b7b.jpg)

Sorry for the bad image quality.

**Comment by dajusc** [comment]
I was expecting that you copy and paste the text, but... OK... ;)

Can you please check if xdotool is installed and working properly? For example by executing the following in your bash:
`xdotool key x`

**Comment by MrWelsch** [comment]
The output for xdotool key x is:
x%

x is input in the prompt after that.

**Comment by dajusc** [comment]
Ok, xdotool seems to be doing fine then.

Maybe an evdev privilege problem. Can you please copy&paste the bash output of `uname -a` and `groups`? Prefereably as text and not as photo. ;)

**Comment by MrWelsch** [comment]
uname -a

Linux Server 5.4.55-1-lts #1 SMP Fri, 31 Jul 2020 17:38:35 +0000 x86_64 GNU/Linux

groups

users input wheel

**Comment by dajusc** [comment]
What happens if you run it as root? This should be done for testing only.

**Comment by MrWelsch** [comment]
One of the first things I tried actually.
Didn’t change anything though.

**Comment by dajusc** [comment]
If I remember correctly, some mice register more than one device. So maybe you could check that by misconfiguring LMKB on purpose like this:
```
lmkb = linuxmousekeybinds("DOESNOTEXIST")
```
If you find other device names related to your mouse, try those.

If this isn't it, I think I am running out of ideas on how to fix this remotely without being able to add e.g. debug outputs to the code.

**Comment by dajusc** [comment]
Update: I just fixed a bug, that LMKB ignored any global bindings (appname=None) for apps that had any app-specific bindings assigned (for any button). Please check if the latest LMKB which includes this fix does solve your problem.

In addition I implemented a debug mode, which you can enable by creating yout LMKB instance likes this:
```
lmkb = linuxmousekeybinds("Your Mouse Name", debug=True)
```

**Comment by MrWelsch** [comment]
Linux Mouse Keybinds started!
DEBUG: Devices: ['Power Button', 'Power Button #2', 'Hoksi Technology DURGOD Venus', 'Hoksi Technology DURGOD Venus System Control', 'Hoksi Technology DURGOD Venus Consumer Control', 'Hoksi Technology DURGOD Venus Keyboard', 'Hoksi Technology DURGOD Venus Mouse', 'Logitec
h MX Master 3', 'Blue Microphones Yeti Stereo Microphone Consumer Control', 'PC Speaker', 'HD-Audio Generic HDMI/DP,pcm=3', 'HD-Audio Generic HDMI/DP,pcm=7', 'HD-Audio Generic HDMI/DP,pcm=8', 'HD-Audio Generic HDMI/DP,pcm=9', 'HD-Audio Generic HDMI/DP,pcm=10', 'HD-Audio G
eneric HDMI/DP,pcm=11', 'HD-Audio Generic Front Mic', 'HD-Audio Generic Rear Mic', 'HD-Audio Generic Line', 'HD-Audio Generic Line Out', 'HD-Audio Generic Front Headphone', 'MX Master 3 Keyboard', 'MX Master 3 Mouse']
DEBUG: Buttons: ['BTN_LEFT', 'BTN_MOUSE', 'BTN_RIGHT', 'BTN_MIDDLE', 'BTN_SIDE', 'BTN_EXTRA', 'BTN_FORWARD', 'BTN_BACK', 'BTN_TASK', 'REL_X+', 'REL_X-', 'REL_Y+', 'REL_Y-', 'REL_HWHEEL+', 'REL_HWHEEL-', 'REL_WHEEL+', 'REL_WHEEL-', 'REL_WHEEL_HI_RES+', 'REL_WHEEL_HI_RES-',
 'REL_HWHEEL_HI_RES+', 'REL_HWHEEL_HI_RES-']

 This was the output of the debug mode which made me realize that apparently there were two different names for the same mouse (First I used "Logitech MX Master 3" which I changed to "MX Master 3 Mouse", Weirdly though I don't even have a MX Master Keyboard which is shown right next to the Mouse.). Changing it to the other name fixed it for me. Thank you very much for all the help!

**Comment by MrWelsch** [comment]
If I may ask one more question:

In which way do you autostart your script?

I tried adding it as a service to systemd in the /etc/systemd/system folder as lmkb.service with -rwxr-xr-x.
lmkb.service is as follows

> [Unit]                                                                                                                                                                                                                                                                                            
> Description=Runs lmkb to enable Extra Mouse Button support.                                                                                       
> After=network.target                                                                                                                                                                                                                                                                                
> [Service]                                                                                                                                                                                                                                                                                            
> Type=simple                                                                                                                                                                                                                                                                                          
> ExecStart=python $HOME/Scripts/mouse/my-lmkb-config.py &                                                                                                                                                                                                                                             
> RemainAfterExit=true                                                                                                                                                                                                                                                                                 
> [Install]                                                                                                                                                                                                                                                                                            
> WantedBy=multi-user.target

Sadly, this does not work.

**Comment by dajusc** [comment]
I'm glad that I could help and happy that I won one more user. ;)

On my Linux Mint Cinnamon (gnome3 derivate) I start LMKB with the desktops "Startup Apps" functionality. This results in LMKB being started at login via a *.desktop file located in my ~/.config/autostart folder.
